# Generated by Django 5.1 on 2024-08-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentrevision',
            options={'get_latest_by': 'created_on', 'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='notebook',
            options={'get_latest_by': 'updated_on', 'ordering': ('-updated_on',)},
        ),
    ]
